# Using CLI 0.32.0 with lib 0.30.1 due to Solana SDK Cargo compatibility
# This causes a warning but builds successfully
[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
seek_protocol = "DqsCXFjgLp4UDZgMQE6nvEHe7yiRNJsVYFv21JSbd73v"

[programs.devnet]
seek_protocol = "DqsCXFjgLp4UDZgMQE6nvEHe7yiRNJsVYFv21JSbd73v"

[programs.mainnet]
seek_protocol = "DqsCXFjgLp4UDZgMQE6nvEHe7yiRNJsVYFv21JSbd73v"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
